### ISSUE TITLE
PyCecClient Running in command prompt

### ISSUE THREAD

**Issue by PAV1THRA** [Pulse-Eight/libcec#265]
I have created an exe file for TV On ,Off and HDMI Source Switching. When I tried executing in the command prompt its working fine. I need to use this exe in a C# application. While integrating getting an error as exe stopped working  when we tried running the same exe by hiding the command prompt. 

Could anyone please help with the issue.

**Comment by opdenkamp** [comment]
I have no idea what error you're getting or what your application is doing exactly. It's very unlikely that libCEC has anything to do with the crash that you're getting.

If you want to use CEC in a C# application, then you should use LibCecSharp instead of calling a command line application. See https://github.com/Pulse-Eight/libcec/blob/master/docs/README.developers.md for more information.
