### ISSUE TITLE
Hibernation emerge 

### ISSUE THREAD

**Issue by Moimemeici** [Pulse-Eight/libcec#281]
Hello, 
First Sorry for my english i'am french.
i use LibCeC with my Dongle Pulse Eigth.
I have ;
Samsung UE55KU6070 (with Anynet+ Activited)
Denon AVR-X1100W (with cec Activited)
PCHD + Dongle CEC (Activited)
Livebox Play (Not HDMI this box is french box for TV)

PCHD (HDMI4) / Livebox (HDMI1)  => Ampli (hdmi in)
ampli (hdmi out) => hdmi => TV (hdmi 1)

When the PCHD is Hibernate.
I use the TV with AV receiver and Livebox Play for see the TV, few minute or instantly , The PCHD comes out of its hibernation and the switch amp on the HDMI port of the PCHD

Sorry for my english

Best Regards.

ps: can you make executable with last driver for windows ?

**Comment by opdenkamp** [comment]
The problem here is that your Livebox doesn't support HDMI-CEC. When your TV powers up, it requests which source is active and, even if your Livebox is selected, it won't respond to this command but the last source that was active (the CEC adapter) will, which will then power on the PC.

If you're using Kodi, go to system -> input devices -> peripherals -> CEC adapter and check "Send inactive source command...". Then press ok. This will tell the TV that Kodi is no longer active when it exits.

New binaries for Windows will be available soon.
