### ISSUE TITLE
Audio device controlled incorrectly

### ISSUE THREAD

**Issue by rtrman** [Pulse-Eight/libcec#396]
I bought the Pulse Eight adapter, in part, to enable me to power on my Philips HTL-5140 sound bar for audio streaming such as Chromecast Audio.

However, I am unable to set the input of the SoundBar via CEC, and it defaults to HDMI ARC on startup, even though I am using Optical In for sound. 
The soundbar responds to most CEC messages, and I can even cycle inputs (using tx 85:44:69), but I cannot **specify** an input; I have tried appending :01 to the message but the soundbar continues to just cycle through its inputs.

I would be grateful for any help with this issue.

**Comment by opdenkamp** [comment]
You normally can't make the soundbar switch to a non-HDMI input through CEC, though it may work by sending RC keys indeed with some AVRs (like yours). CEC doesn't specify any way to make your AVR switch to a specific input.

If you're sending RC keys (opcode 0x44), then you have to send a key up too (opcode 0x45):
```
tx 85:44:69
tx 85:45
```
I guess that's why it's cycling here, but I'd have to see the log output from cec-client to see what's happening exactly if 0x45 doesn't help
