### ISSUE TITLE
USB Adapter isn't being recognize by AVR and/or LG TV

### ISSUE THREAD

**Issue by AppleTechy** [Pulse-Eight/libcec#399]
So I bought the adapter to use inline between my TiVo and my  Yamaha AVR unit. I followed the install instructions.  Here is the info about the RPI, its a Pi 2`Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch`
When I run scan `echo "scan" | cec-client /dev/ttyACM0 -s -d 1` here is the output, [Link to Imgur Pictures](https://imgur.com/a/EJDFh). The Tivo is plugged into HDMI port 3 on my AVR and the AVR is plugged into the TV in port 2. I had been trying to run 'cec-client -b 2 -p 3  -t r -o TiVo`. It successfully opens up the connection to the USB Adapter but the AVR never recognizes it as a CEC device. I even tried plugging the adapter directly into the TV bypassing the AVR, and the LG TV still wouldn't pick up the OSD name I was setting. When I turn on the TV and the AVR, the AVR switches to AV4 but still passes through the video, when without the adapter it immediately switches to the Apple TV, so the Adapter seems to be working, I just don't know why the broadcast seems to have the AVR think the source doesn't have audio. Has anyone else had this issue? I appreciate any advice you guys have. I also can provide logs, if there are any in-specific that are needed to diagnose this.

**Comment by opdenkamp** [comment]
If you want to tell libCEC that the adapter is connected to HDMI of the AVR, then you need these parameters: `cec-client -b 5 -p 3`. The AVR uses logical address 5.
But if you're running cec-client while X is running (in a GUI), then you should not need those parameters.

If you want your TV to pick up an OSD name, then you have to keep cec-client running, so not pass the `-s` parameter. You can't just send an OSD name and close cec-client, because CEC doesn't support this.
