### ISSUE TITLE
Using LibCecSharp on raspbian or other linux distro

### ISSUE THREAD

**Issue by olegsavelos** [Pulse-Eight/libcec#437]
Is it possible to use the library with .net core on raspbian?
Or is its only possible to use it on windows ?

**Comment by opdenkamp** [comment]
LibCecSharp is a .net v2.0 wrapper around libcec.dll, built with the Visual Studio 2008 toolchain. The reason is backwards compatibility.

This won't work on Linux, even if .net core would be fully compatible down to v2.0 and uses Wine under the hood to load dlls, because it wouldn't be able to talk to the adapter.
