### ISSUE TITLE
Make build reproducible

### ISSUE THREAD

**Issue by jelly** [Pulse-Eight/libcec#485]
The current libcec cannot be built twice on different machines since it [records the buildtime](https://tests.reproducible-builds.org/archlinux/community/libcec/libcec-4.0.4-2-x86_64.pkg.tar.xz.html) in the binary. A solution is to honour SOURCE_DATE_EPOCH which is described on the reproducible builds website https://reproducible-builds.org/

**Comment by bmwiedemann** [comment]
in openSUSE we workaround it with
https://github.com/bmwiedemann/openSUSE/blob/master/packages/libc/libcec/libcec-build-compare.patch

but since it is cmake, one can use the TIMESTAMP macro to be more portable and provide reproducible builds at the same time. See #487 for that.

There are also build user, host and kernel version.
