### ISSUE TITLE
LibCecSharp unable to load cec.dll when creating UWP app

### ISSUE THREAD

**Issue by hatharry** [Pulse-Eight/libcec#496]
When creating a uwp app the debugger throws this error (creating a console app works fine):

DllNotFoundException: Unable to load DLL '' or one of its dependencies: Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))

**Comment by opdenkamp** [comment]
.Net Core (UWP) will be supported in the upcoming libCEC release. I've just pushed the changes to master: https://github.com/Pulse-Eight/libcec/commit/d5e5200ed1a998af24fa5290ad764e0a2ed086c6

You can't use the .Net Framework version of the library (LibCecSharp) on UWP because it's not compatible, but you'll have to reference the new LibCecSharpCore.

also, cec.dll is no longer required to be present in the directory when building .Net application in this new release
