### ISSUE TITLE
CEC with Kodi/Pulseeight-Adapter + AVR, but without CEC-capable TV/Projector

### ISSUE THREAD

**Issue by J4nsen** [Pulse-Eight/libcec#657]
Hi,
I want to control my HTPC with my AVR remote. My foolish assumption was that I just need to buy a Pulseeight HDMI Cec adapter to be able to control my HTPC running Kodi. 
In my setup I have a Sony projector  (VPL-XW5000ES) that does *not* support HDMI CEC. 

As I just found out, the HDMI CEC spec seems to requires a TV to be present. :( Everything works fine if I connect a TV with CEC support, but nothing happens if the projector is connected to the AVR.

Is there any way around this? 
 * Can a second Pulseeight adapter act as TV?
 * Can one single adapter be a TV and a playback device? 
 * Is there another product which emulates a TV?

### Logs
I have four logs of cec-client
* [cec-client: scan with projector](https://github.com/Pulse-Eight/libcec/files/15239990/scan-projector.txt)
* [cec-client: scan with tv](https://github.com/Pulse-Eight/libcec/files/15239991/scan-tv.txt)
* [cec-client: button press on AVR remote with projector](https://github.com/Pulse-Eight/libcec/files/15239988/button_press-projector.txt) (OK button of AVR remote pressed on timestamp 7039)
* [cec-client: button press on AVR remote with TV](https://github.com/Pulse-Eight/libcec/files/15239989/button_press-tv.txt) (OK button of AVR remote pressed on timestamp 6500)

### Hardware
 * AVR: Yamaha RX-A4A
 * HTPC: Windows 11 x64 with Kodi + Pulseeight HDMI CEC Adapter
 * Projector: Sony VPL-XW5000ES
 * TV: Toshiba 40VL748

Any ideas are very much appreciated :)

**Comment by malard** [comment]
Hi,

Our client wont do this natively, you would need to make changes to the code to do it.

Thanks

From: Jan Wiele ***@***.***>
Sent: Tuesday, May 7, 2024 8:33 PM
To: Pulse-Eight/libcec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Pulse-Eight/libcec] CEC with Kodi/Pulseeight-Adapter + AVR, but without CEC-capable TV/Projector (Issue #657)


Hi,
I want to control my HTPC with my AVR remote. My foolish assumption was that I just need to buy a Pulseeight HDMI Cec adapter to be able to control my HTPC running Kodi.
In my setup I have a Sony projector (VPL-XW5000ES) that does not support HDMI CEC.

As I just found out, the HDMI CEC spec seems to requires a TV to be present. :( Everything works fine if I connect a TV with CEC support, but nothing happens if the projector is connected to the AVR.

Is there any way around this?

  *   Can a second Pulseeight adapter act as TV?
  *   Can one single adapter be a TV and a playback device?
  *   Is there another product which emulates a TV?

Logs

I have four logs of cec-client

  *   cec-client: scan with projector<https://github.com/Pulse-Eight/libcec/files/15239990/scan-projector.txt>
  *   cec-client: scan with tv<https://github.com/Pulse-Eight/libcec/files/15239991/scan-tv.txt>
  *   cec-client: button press on AVR remote with projector<https://github.com/Pulse-Eight/libcec/files/15239988/button_press-projector.txt> (OK button of AVR remote pressed on timestamp 7039)
  *   cec-client: button press on AVR remote with TV<https://github.com/Pulse-Eight/libcec/files/15239989/button_press-tv.txt> (OK button of AVR remote pressed on timestamp 6500)

Hardware

  *   AVR: Yamaha RX-A4A
  *   HTPC: Windows 11 x64 with Kodi + Pulseeight HDMI CEC Adapter
  *   Projector: Sony VPL-XW5000ES
  *   TV: Toshiba 40VL748

Any ideas are very much appreciated :)
